name: build

on:
  workflow_call:
    outputs:
      IMAGE_VERSION:
        value: ${{ jobs.build.outputs.IMAGE_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_VERSION: ${{ steps.foo.outputs.IMAGE_VERSION }}
    steps:
      - id: foo
        run: |
          echo IMAGE_VERSION=aaaa >> "$GITHUB_OUTPUT"
