name: ghcr-push

on:
  push:
    branch:
      - '*'
    tags:
      - '*'

jobs:
  ghcr-push:
    runs-on: macos-latest
    steps:
      - run: |
          brew list
          brew --prefix --installed openssl
      - uses: Raku/setup-raku@v1
      - run: |
          zef install OpenSSL
