name: ghcr-push

on:
  push:
    branches:
      - '*'

jobs:
  ghcr-push:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Raku/setup-raku@v1
      - if: matrix.os == 'macOS-latest'
        run: brew install openssl
      - run: |
          zef install --/test OpenSSL
