name: lib

on:
  workflow_call:
    inputs:
      service:
        description: テスト
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AAA: "${{ inputs.service == 'foo' && 'aaaaaaaa' || 'default' }}.yml"
      BBB: "${{ inputs.service }}"
    steps:
      - run: env | sort
