name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Perl
        run: curl -fsSL https://git.io/perl-install | bash -s ~/perl
      - name: perl -V
        run: ~/perl/bin/perl -V
      - name: Run Tests
        run: ~/perl/bin/perl test.pl
