name: release

on:
  push:

jobs:

  macos:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rakudo
        run: |
          curl -fsSL -o rakudo-moar-2020.02.1-01-win-x86_64.zip https://rakudo.org/dl/rakudo/rakudo-moar-2020.02.1-01-win-x86_64.zip
          unzip rakudo-moar-2020.02.1-01-win-x86_64.zip
          pwd
          rakudo-2020.02.1\bin\raku -V
