name: release

on:
  push:

jobs:

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rakudo
        run: |
          curl -fsSL -o rakudo-moar-2020.02.1-01-win-x86_64.zip https://rakudo.org/dl/rakudo/rakudo-moar-2020.02.1-01-win-x86_64.zip
          unzip -q rakudo-moar-2020.02.1-01-win-x86_64.zip
          $pwd = [System.IO.Directory]::GetCurrentDirectory()
          echo "##[add-path]$pwd\rakudo-2020.02.1\bin;$pwd\rakudo-2020.02.1\share\perl6\site\bin"
          rakudo-2020.02.1\bin\raku --version
      - name: Install Dependencies
        run: zef install --/test App::Prove6
      - name: Run Tests
        run: prove6 -l t
