name: test

on:
  - push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'
      - run: |
          curl -fsSL https://raw.githubusercontent.com/skaji/cpm/terminal-logger-test/cpm > cpm
          perl cpm install Plack
