name: test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          env -u GITHUB_ACTIONS brew link --force xz
