name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - run: echo hello > hello.txt
      - uses: sigstore/gh-action-sigstore-python@v3.3.0
        with:
          inputs: hello.txt
      - run: ls -al
