name: test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.14'
      - run: |
          perl -V
          cpanm -V
          cpanm -nq App::FatPacker
          curl -fsSL https://git.io/cpm | perl - install --reinstall App::FatPacker
