name: test

on:
  push:
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.32'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.perl-cpm/builds
          key: ${{ runner.os }}-${{ matrix.perl-version }}
      - run: curl -fsSL --compressed https://git.io/cpm | perl - install -g Dist::Zilla
