name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    runs-on: windows-latest
    steps:
      - run: cpanm --version
      - run: cpanm -Ltest1 -v Text::CharWidth
