name: test

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macOS-11.0
    steps:
      - run: |
          which -a perl
          brew install perl openssl@1.1
          /usr/local/bin/perl -v
          curl -fsSL https://git.io/cpm | /usr/local/bin/perl - install Net::SSLeay JSON::XS
