name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_VERSION: ${{ steps.foo.outputs.IMAGE_VERSION }}
    steps:
      - id: foo
        run: |
          echo IMAGE_VERSION=aaaa >> "$GITHUB_OUTPUT"
  test2:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: |
          echo ${{ needs.test.outputs.IMAGE_VERSION }}


