name: test

on:
  - push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.8'
      - run: |
          perl -V
          perl -le 'for my $v (@ARGV) { eval "require $v; print qq[$v ], $v->VERSION" or print "$v missing" }' Module::Build Test::Harness ExtUtils::MakeMaker Module::Metadata
