name: test

on:
  push:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  test2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo ${{ needs.build.outputs.IMAGE_VERSION }}


