name: test

on:
  - push

jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh repo list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
