name: test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.14'
      - run: |
          curl -fsSL https://git.io/cpm -o cpm
          perl find.pl
          perl exec-without-perl5lib.pl perl cpm install --verbose App::FatPacker
