name: test

on:
  - push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: test
        run: |
          set -euxo pipefail
          docker buildx build --platform linux/amd64 --build-arg IMAGE=centos:centos6 -t test-amd64 --load .
          docker buildx build --platform linux/arm64 --build-arg IMAGE=centos:centos7 -t test-arm64 --load .
          ID_AMD64=$(docker create --platform linux/amd64 test-amd64)
          ID_ARM64=$(docker create --platform linux/arm64 test-arm64)
          docker cp $ID_AMD64:/etc/redhat-release redhat-release-amd64.txt
          docker cp $ID_ARM64:/etc/redhat-release redhat-release-arm64.txt
          docker rm $ID_AMD64
          docker rm $ID_ARM64
          ls -al
          cat redhat-release-amd64.txt
          cat redhat-release-arm64.txt
