name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chown root:root .
          curl -fsSL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s -- -b $GOPATH/bin
          golangci-lint run --verbose --timeout=5m
