name: test

on:
  - push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: test
        run: |
          docker buildx build --platform linux/amd64 -t test-amd64 --load .
          docker buildx build --platform linux/arm64 -t test-arm64 --load .
          docker run test-amd64 uname -a
          docker run test-arm64 uname -a
