name: test

on:
  - push

jobs:
  test:
    defaults:
      run:
        shell: 'script -q -e -c "bash {0}"'
    runs-on: ubuntu-latest
    container:
      image: perl:latest
    steps:
      - uses: actions/checkout@v2
      - run: cpanm -nq Capture::Tiny
      - run: cpanm
        shell: bash
      - run: cpanm --unknoooooo
        shell: bash
      - run: perl test.pl
        shell: bash
