name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull kennethreitz/httpbin
      - run: docker run -d -p 8080:80 kennethreitz/httpbin
      - run: docker ps -a
      - run: curl -fsSL http://localhost:8080/ip
