name: test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        include:
          - service: foo
          - service: hoge
    uses: ./.github/workflows/lib.yml
    with:
      service: ${{ matrix.service }}

