name: test

on:
  push:
    branch:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.20'
      - run: cpanm -n -v CPAN::Test::Dummy::Perl5::StaticInstall
