name: test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        perl-version:
          - '5.16'
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: perl -MNet::SSLeay -e1
