name: test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: perl:latest
    steps:
      - uses: actions/checkout@v2
      - run: cpanm -nq Capture::Tiny
      - run: cpanm
      - run: cpanm --unknoooooo
      - run: perl test.pl
