name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  test:

    runs-on: macOS-latest

    strategy:
      matrix:
        perl-version:
          - '5.10'
          - '5.12'
          - '5.14'
          # - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'

    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1.3.0
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: |
          set +e
          curl -fsSL -o cpm https://raw.githubusercontent.com/skaji/cpm/investigate/cpm
          for i in {1..10}; do
            rm -rf ~/.perl-cpm local
            perl cpm install Plack
            if [[ $? -ne 0 ]]; then
              cat ~/.perl-cpm/build.log
              exit 1
            fi
            if grep -q Retrying ~/.perl-cpm/build.log; then
              cat ~/.perl-cpm/build.log
              exit 1
            fi
          done
