name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - run: echo hello > foo.txt
      - uses: sigstore/cosign-installer@v4.1.2
      - run: cosign sign-blob foo.txt --bundle foo.txt.sigstore.json --yes
      - uses: actions/upload-artifact@v6
        with:
          path: |
            foo.txt
            foo.txt.sigstore.json
