name: test

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ github.event.release.tag_name }}
          echo ${{ github.event.ref }}
          echo ${GITHUB_REF##*/}
