name: test

on: [push, pull_request]

jobs:
  perl:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: perl -V
      - run: curl -fsSL https://git.io/cpm | perl - install -g IPC::Run3
      - run: perl test.pl
