name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - windows-latest
        raku-version:
          - latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Dependencies
        run: |
          perl -e die
          perl -e "warn q(OK)"
