name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -fsSL https://rakudo.org/dl/rakudo | jq -r '[sort_by(.build_rev) | reverse | .[] | select(.ver == "2020.05.1" and .format == "zip" and .arch == "x86_64" and .platform == "win") | .url][0]'
