name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          perl -V
          choco install strawberryperl
          echo "::add-path::C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
          perl -V
